calendarapp/urls.py
from django.urls import path
from calendarapp.views.other_views import TutoriaCreateView, formCalendarioFuncDoc, obtener_horarios_cita ,EditCalendarioFuncDoc, tipo_cita, tipo_acti_academ, AddCalendarioFuncDoc, delCalendarioFuncDoc, ori_academica, actualizar_campo, CitaTutoriaCreateView, CitaOrientacionAcademicaCreateView, CitaTutoriaUpdateView, CitaOrientacionAcademicaUpdateView, CitaTutoriaDetalle, CitaOrientacionAcademicaDetalle, CitaTutoriaIniciarView, CitaOrientacionAcademicaIniciarView, OrientacionAcademicaCreateView, TutoriaDetalle, OrientacionAcademicaDetalle, TutoriaUpdateView, TareasView, OrientacionAcademicaUpdateView, AddTarea#ListCalendarioFuncDoc

from calendarapp.views import CalendarView, CalendarViewNew, AllEventsListView, RunningEventsListView, DetalleCita, CancelarCita
from calendarapp.views.event_list import AprobarCita, ActividadesAcademicasListView, RunningActividadesAcademicasListView, DetalleActividadesAcademicas, CancelarActividadAcademica, FinalizarActividadAcademica, CancelarTarea, IniciarTarea, FinalizarTarea, About, RechazarCita
from calendarapp.views.reportes import ReporteTutoriaView, actualizar_campos_reportes, ReporteOrientacionAcademicaView, ReporteCitasView, ReporteTareasView
app_name = "calendarapp"


urlpatterns = [
    
    path("formulariofundoc/", formCalendarioFuncDoc, name="form_cal_func_doc"),
    path("formulariofundoc/edit/<int:pk>/", EditCalendarioFuncDoc, name="edit_cal_func_doc"),
    path("formulariofundoc/add/", AddCalendarioFuncDoc, name="add_cal_func_doc"),
    path("formulariofundoc/delete/<int:pk>/", delCalendarioFuncDoc, name="del_cal_func_doc"),
    path("calender/", CalendarViewNew.as_view(), name="calendar"), #este es el calendario
    path("calenders/", CalendarView.as_view(), name="calendars"), #este es el dashboard
    
    #Citas
    path("tipoCita/", tipo_cita, name="tipo_cita"),
    path('actualizar_campo/', actualizar_campo, name='actualizar_campo'),
    path("detallesCita/<int:id_cita>/", DetalleCita, name="detalles_cita"),
    path("cita/confirmar/<int:id_cita>/", AprobarCita, name="confirmar_cita"),
    path("cita/cancelar/<int:id_cita>/", CancelarCita, name="cancelar_cita"),
    path("cita/rechazar/<int:id_cita>/", RechazarCita, name="rechazar_cita"),
    path("tutoria/", CitaTutoriaCreateView.as_view(), name="tuto"),
    path("orientacionAcademica/", CitaOrientacionAcademicaCreateView.as_view(), name="academica"),
    path("modificarCitaTutoria/<int:pk>/", CitaTutoriaUpdateView.as_view(), name="modificar_cita_tutoria"),
    path("modificarCitaOriAcademica/<int:pk>/", CitaOrientacionAcademicaUpdateView.as_view(), name="modificar_cita_ori_academica"),
    path('obtener_horarios_cita/', obtener_horarios_cita),
    path("all-event-list/", AllEventsListView.as_view(), name="all_events"),
    path("running-event-list/<str:tipo_cita>/",RunningEventsListView.as_view(),name="running_events"), 
    path("moredetallesCitaTutoria/<int:pk>/", CitaTutoriaDetalle.as_view() , name="more_detalles_cita_tutoria"),
    path("moredetallesCitaOriAcadem/<int:pk>/", CitaOrientacionAcademicaDetalle.as_view() , name="more_cita_detalles_ori_academica"),
    path("iniciarCitaTutoria/<int:pk>/", CitaTutoriaIniciarView.as_view() , name="iniciar_cita_tutoria"),
    path("iniciarCitaOrientacionAcademica/<int:pk>/", CitaOrientacionAcademicaIniciarView.as_view() , name="iniciar_cita_ori_academ"),
    
    
    
    
    #Actividades Academicas
    path("tipoActiAcadem/", tipo_acti_academ, name="tipo_acti_academ"),
    path("all-acti_academ-list/", ActividadesAcademicasListView.as_view(), name="all_acti_academ"),
    path("running-acti_academ-list/<str:tipo_cita>/",RunningActividadesAcademicasListView.as_view(),name="running_acti_academ"), 
    path("actiAcademTutoria/", TutoriaCreateView.as_view(), name="acti_academ_tutoria"),
    path("actiAcademOrientacion/", OrientacionAcademicaCreateView.as_view(), name="acti_academ_orientacion"),
    path("detallesActiAcademicas/<int:id_tutoria>/<int:id_ori_academ>/", DetalleActividadesAcademicas, name="detalles_acti_academ"),
    path("moredetallesTutoria/<int:pk>/", TutoriaDetalle.as_view() , name="more_detalles_tutoria"),
    path("moredetallesOrientacionAcademica/<int:pk>/", OrientacionAcademicaDetalle.as_view() , name="more_detalles_ori_academica"),
    path("actividad_academica/cancelar/<int:id_tutoria>/<int:id_ori_academ>/", CancelarActividadAcademica, name="cancelar_actividad_academica"),
    path("actividad_academica/finalizar/<int:id_tutoria>/<int:id_ori_academ>/", FinalizarActividadAcademica, name="finalizar_actividad_academica"),
    path("modificarTutoria/<int:pk>/", TutoriaUpdateView.as_view(), name="modificar_tutoria"),
    path("modificarOrientacion/<int:pk>/", OrientacionAcademicaUpdateView.as_view(), name="modificar_orientacion"),
    
    #Tareas
    path("tareas/", TareasView.as_view(), name="tareas"),
    path("tarea/finalizar/<int:id_tarea>/", FinalizarTarea, name="finalizar_tarea"),
    path("tarea/iniciar/<int:id_tarea>/", IniciarTarea, name="iniciar_tarea"),
    path("tarea/cancelar/<int:id_tarea>/", CancelarTarea, name="cancelar_tarea"),
    path("nuevaTarea/", AddTarea, name="nueva_tarea"),
    
    
    #adicionales
    path("about/", About, name="about"),
    
    
    #reportes
    path("reporte/tutoria/", ReporteTutoriaView.as_view(), name="reporte_tutoria"),
    path("reporte/cita/", ReporteCitasView.as_view(), name="reporte_cita"),
    path("reporte/orientacion/", ReporteOrientacionAcademicaView.as_view(), name="reporte_orientacion"),
    path("reporte/tarea/", ReporteTareasView.as_view(), name="reporte_tarea"),
    path('actualizar_campos_reportes/', actualizar_campos_reportes, name='actualizar_campos_reportes'),
    
    
    
    
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
    path("", include("notify.urls")),
]

notify/urls.py
from django.urls import path
from notify.views import NotificationList, actualizar_notificacion_leida

app_name = "notify"

urlpatterns = [
    path("notificacion/", NotificationList.as_view(), name="notificaciones"),
    path("actualizarNotify/", actualizar_notificacion_leida, name="actualizar_notificacion"),
]

calendarapp/models/event_abstract.py
from django.db import models



class EventAbstract(models.Model):
    """ Event abstract model """

    id_actividad_academica= models.AutoField(primary_key=True)

    class Meta:
        abstract = True

calendarapp/models/event_member.py
from django.db import models

from accounts.models import User
from calendarapp.models import Event, EventAbstract



class EventMember(EventAbstract):
    """ Event member model """

    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="events")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="event_members"
    )

    class Meta:
        unique_together = ["event", "user"]

    def __str__(self):
        return str(self.user)

calendarapp/views/event_list.py
import json
from django.forms import model_to_dict
from django.views.generic import ListView
from django.shortcuts import render
from accounts.models.user import Persona
from calendarapp.models import Event
from calendarapp.models.event import Cita, EstadoActividadAcademica,DetalleActividadAcademica, Tutoria, OrientacionAcademica, Tarea, EstadoTarea, DetalleActividadAcademica
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib import messages
from django.http import HttpResponse
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from accounts.models.user import FuncionarioDocente
from itertools import chain
from django.db.models import Q,  F, Case, When, Value, IntegerField, DateTimeField
from django.db.models.functions import Coalesce
from django.utils.decorators import method_decorator
zona_horaria_py = 'Etc/GMT-4'
import pytz

# Función para extraer la fecha de cada tipo de objeto
def get_fecha(event):
    if isinstance(event, Tutoria):
        if event.id_tutoria.datetime_inicio_real:
            return event.id_tutoria.datetime_inicio_real
        else:
            return event.id_tutoria.datetime_inicio_estimado
    elif isinstance(event, OrientacionAcademica):
        if event.id_orientacion_academica.datetime_inicio_real:
            return event.id_orientacion_academica.datetime_inicio_real
        else:
            return event.id_orientacion_academica.datetime_inicio_estimado
        
class AllEventsListView(ListView):
    """ All event list views """

    template_name = "calendarapp/events_list.html"
    model = Event
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # Devuelve un queryset vacío
        return Event.objects.none()
    
    def get_citas(self):
        try:
            lista_eventos= []
            fecha= ''
            dia= ''
            horario= ''
            estado= ''
            encargado= ''
            solicitante= ''
            tipo= '' 
            id= ''
            tipo_usuario= ''
            dias_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]
            request = self.request
            current_user= request.user
            dict = model_to_dict(current_user)
            ins_persona=  Persona.objects.get(id= dict["id_persona"])
            #devolvemos solo aquellos registros que correspondan al usuario logeado
            if current_user.has_perm('calendarapp.iniciar_cita'):
                ins_funcionario_docente= FuncionarioDocente.objects.get(id_funcionario_docente= ins_persona)
                event= Event.objects.get_all_events().filter(id_cita__id_funcionario_docente_encargado= ins_funcionario_docente)
                # Anotar el queryset con una expresión que determine el campo de ordenamiento
                event = event.annotate(
                    datetime_to_order=Case(
                        When(id_cita__datetime_inicio_real__isnull=False, then=F('id_cita__datetime_inicio_real')),
                        default=F('id_cita__datetime_inicio_estimado')
                    )
                )

                event = event.order_by('-datetime_to_order')
                
                if event.exists():
                    for objeto in event:
                            if objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica not in ('Finalizada', 'Cancelada', 'Rechazada') and objeto.id_cita.datetime_fin_estimado <= datetime.now():
                                objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica = 'Vencida'
                            if objeto.id_cita.datetime_inicio_real:
                                fecha= objeto.id_cita.datetime_inicio_real.strftime('%d-%m-%Y')
                                dia= objeto.id_cita.datetime_inicio_real.weekday()
                                dia= dias_semana[dia]
                                horario= objeto.id_cita.datetime_inicio_real.strftime('%H:%M:%S')
                            else:
                                fecha= objeto.id_cita.datetime_inicio_estimado.strftime('%d-%m-%Y')
                                dia= objeto.id_cita.datetime_inicio_estimado.weekday()
                                dia= dias_semana[dia]
                                horario= objeto.id_cita.datetime_inicio_estimado.strftime('%H:%M:%S')
                            encargado= str(objeto.id_cita.id_funcionario_docente_encargado)
                            solicitante= objeto.id_cita.id_persona_alta.nombre + ' ' + objeto.id_cita.id_persona_alta.apellido
                            
                            estado= str(objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica)
                            if objeto.es_tutoria== True:
                                tipo= 'Tutoría'
                            elif  objeto.es_orientacion_academica== True:
                                tipo= 'Orientación Académica'
                            id= str(objeto.id_cita.id_actividad_academica)
                            tipo_usuario= 'staff'
                            
                            auxiliar= {'fecha': fecha, 'dia': dia, 'horario': horario, 'estado': estado, 'encargado': encargado, 'solicitante': solicitante, 'tipo': tipo, 'id': id, 'tipo_usuario': tipo_usuario}                    
                            lista_eventos.append(auxiliar) 
                return lista_eventos
                
            else:
                event_= Event.objects.get_all_events().filter(id_cita__id_persona_alta= ins_persona).annotate(
                    datetime_to_order=Case(
                        When(id_cita__datetime_inicio_real__isnull=False, then=F('id_cita__datetime_inicio_real')),
                        default=F('id_cita__datetime_inicio_estimado'),
                        output_field=DateTimeField()
                    )
                )
                
                participante_cita= DetalleActividadAcademica.objects.filter(id_participante= ins_persona).values('id_actividad_academica')
                
                events_participante= Event.objects.get_all_events().filter(id_cita__id_actividad_academica__in= participante_cita).annotate(
                    datetime_to_order=Case(
                        When(id_cita__datetime_inicio_real__isnull=False, then=F('id_cita__datetime_inicio_real')),
                        default=F('id_cita__datetime_inicio_estimado'),
                        output_field=DateTimeField()
                    )
                )
                
                #unimos ambos registros
                if events_participante.exists():                 
                    event = event_.union(events_participante)
                else:
                    event= event_

                event = event.order_by('-datetime_to_order')
                
                if event.exists():
                    for objeto in event:
                            if objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica not in ('Finalizada', 'Cancelada', 'Rechazada') and objeto.id_cita.datetime_fin_estimado <= datetime.now():
                                objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica = 'Vencida'
                            if objeto.id_cita.datetime_inicio_real:
                                fecha= objeto.id_cita.datetime_inicio_real.strftime('%d-%m-%Y')
                                dia= objeto.id_cita.datetime_inicio_real.weekday()
                                dia= dias_semana[dia]
                                horario= objeto.id_cita.datetime_inicio_real.strftime('%H:%M:%S')
                            else:
                                fecha= objeto.id_cita.datetime_inicio_estimado.strftime('%d-%m-%Y')
                                dia= objeto.id_cita.datetime_inicio_estimado.weekday()
                                dia= dias_semana[dia]
                                horario= objeto.id_cita.datetime_inicio_estimado.strftime('%H:%M:%S')
                            encargado= str(objeto.id_cita.id_funcionario_docente_encargado)
                            solicitante= objeto.id_cita.id_persona_alta.nombre + ' ' + objeto.id_cita.id_persona_alta.apellido
                            id_solicitante= objeto.id_cita.id_persona_alta.id
                            
                            estado= str(objeto.id_cita.id_estado_actividad_academica.descripcion_estado_actividad_academica)
                            if objeto.es_tutoria== True:
                                tipo= 'Tutoría'
                            elif  objeto.es_orientacion_academica== True:
                                tipo= 'Orientación Académica'
                            id= str(objeto.id_cita.id_actividad_academica)
                            tipo_usuario= 'normal'
                            
                            auxiliar= {'fecha': fecha, 'dia': dia, 'horario': horario, 'estado': estado, 'encargado': encargado, 'solicitante': solicitante, 'tipo': tipo, 'id': id, 'tipo_usuario': tipo_usuario, 'id_solicitante': id_solicitante}                    
                            lista_eventos.append(auxiliar) 
                
                return lista_eventos
                
        except Exception as e:
            print(f"Se ha producido un error en obtener lista de citas: {e}")
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['citas'] = self.get_citas()
        return context

class ActividadesAcademicasListView(ListView):
    """ All event list views """

    template_name = "calendarapp/actividades_academicas_list.html"
    model = Event
    
    

templates/calendarapp/about.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div>
                        <div class="row">
                            <div class="col-sm-12">

                                    <h3> <label class="label texto-destacado">Sobre el sistema:</label>  </h3>
                                    <div class="col-sm-10">
                                        <p>AcOms es un Sistema de Gestión y Seguimiento de citas, tutorías y orientaciones académicas por sus siglas en inglés (Academic Orientation Managment System) que fue desarrollado por un alumno de la Facultad de Ciencias y Tecnología de la Universidad Autónoma de Asunción. El propósito de esta solución es ofrecer una herramienta que facilite a los alumnos la solicitud de citas con los funcionarios y/o docentes de la facultad para realizar tutorías y orientaciones académicas (ambas denominadas actividades académicas) que requieran de gestiones posteriores y un seguimiento adecuado hasta su finalización.
                                        </p> 
                                    </div>
                                  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

{% block extrascripts %}



<script> 

    $(document).ready(function() {

        $('#AboutMenu').addClass('active');
    });

</script> 
{% endblock extrascripts %}

templates/calendarapp/calendario_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="tile-body">
                <div class="table-responsive">
                    <div class="tile">
                        <div>
                            <a type="button" class="btn btn-primary mt-2" href="{% url 'calendarapp:add_cal_func_doc' %}">
                                Agregar
                            </a>
                        </div>
                        <br>

                        <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                    <table class="table table-hover table-bordered dataTable no-footer" id="tblHorarios" role="grid" aria-describedby="sampleTable_info">
                                        <thead>
                                            <tr role="row">
                                               <th>Convocatoria</th>  
                                                <th >Dia</th>
                                                <th >Hora Inicio</th>
                                                <th >Hora Fin</th>
                                                <th >Opciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modalEvent" class="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document"> 
        
    </div>
</div>

{% endblock content %}

{% block extrascripts %}
<link rel="stylesheet" href="{% static 'lib_extras/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
<link rel="stylesheet" href="{% static 'lib_extras/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
<script src="{% static 'lib_extras/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib_extras/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib_extras/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib_extras/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
 <!-- Jquery Confirm -->
 <link rel="stylesheet" href="{% static 'lib_extras/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
 <script src="{% static 'lib_extras/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
 <!-- Functions -->
 <script src="{% static 'js/functions.js' %}"></script>

    <script>

        var tblHorarios;
        var lista_Horarios = {{ dict_cal_fun_doc|safe }}

        $(document).ready(function() {

            $('#AdminCalendarioMenu').addClass('active');


            tblHorarios = $('#tblHorarios').DataTable({
                responsive: true,
                //scrollX: true,
                autoWidth: false,
                destroy: true,
                deferRender: true,
                data: lista_Horarios,
                columns: [
                    {"data": "convocatoria"},
                    {"data": "dia"},
                    {"data": "hora_inicio"},
                    {"data": "hora_fin"},
                    {
                        "data": null,
                        "render": function(data, type, row) {
                             return '<a rel="editar" class="btn btn-primary" style="color: white;" title="Editar" href="/formulariofundoc/edit/' + row.id + '">Editar</a> <a rel="eliminar" class="btn btn-danger" style="color: white;" title="Eliminar" value="/formulariofundoc/delete/' + row.id + '"> Eliminar </a>';
                        }
                    }
                ],
                order: [] 
            });

            $('#tblHorarios').on('click', 'a[rel="eliminar"]', function(event) { 
                event.preventDefault();
            
                // Obtener la URL del valor del atributo "value" del elemento <a>
                var url = $(this).attr("value");
                    
                // Obtener el elemento modal
                var modal = $('#modalEvent');

                // Realizar una solicitud AJAX para cargar el contenido
                $.get(url, function(data) {
                    //console.log(data)
                    // Insertar el contenido en el elemento con la clase "modal-dialog"
                    modal.find('.modal-dialog').html(data);

                    // Mostrar el modal
                    modal.modal('show');
                });
            });


        });
    </script>

{% endblock extrascripts %}

templates/calendarapp/form_hora_sem_func_doc.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}
<form  action="{{request.path}}" class="modal-content" method="post">
    {% csrf_token %}
      <div class='modal-header text-center'>
        <h3 class="modal-title w-100">Horario Semestral</h3> 
      </div>


      <p class="or">
      {% if form.errors %}
        <ul class="errorlist">
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <span class="text-danger"> <li>{{ error }}</li> </span>
            {% endfor %}
          {% endfor %}
        </ul>
      {% endif %}
      </p>

      <div class="modal-body">
        <div class="col-md-12">
          <div class="form-group">
            <label class="label" for="id_funcionario_docente">Funcionario/Docente</label> 
            {{ form.id_funcionario_docente}} 
             <span class="text-danger">{{ form.errors.id_funcionario_docente }}</span>
          </div>
        </div> 


      <div class="modal-body">
        <div class="col-md-12">
          <div class="form-group">
            <label class="label" for="id_convocatoria">Convocatoria</label>
            {{ form.id_convocatoria}}
            <span class="text-danger">{{ form.errors.id_convocatoria }}</span>
          </div>
        </div>
    
        <div class="col-md-12">
          <div class="form-group">
            <label class="label" for="id_dia">Dia</label>
            {{ form.id_dia }}
            <span class="text-danger">{{ form.errors.id_dia }}</span>
          </div>
        </div>
        <div class="col-md-12">
          <div class="form-group">
              <label class="label" for="hora_inicio">Hora Inicio</label>
              {{ form.hora_inicio }}
              <span class="text-danger">{{ form.errors.hora_inicio }}</span>
            </div>
        </div>

        <div class="col-md-12">
          <div class="form-group">
              <label class="label" for="hora_fin">Hora Fin</label>
              {{ form.hora_fin }}
              <span class="text-danger">{{ form.errors.hora_fin }}</span>
            </div>
        </div>
    
        <div class="modal-footer">
          {% comment %} cuidado con las versiones de Bootstrap! {% endcomment %}
          <a type="button" class="btn btn-secondary" data-dismiss="modal" href="{% url 'calendarapp:form_cal_func_doc' %}">Cancelar</a>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>  
            
      </div>
    </form>  

{% endblock content %}
  {% comment %} {% block extrascripts %}
        <!-- Agregue este código JavaScript al final de la plantilla -->
        <script>
          // Obtenga el modal
          var modal2 = new bootstrap.Modal(document.getElementById("modal"));
          console.log(modal2);

          // Cuando se envía el formulario, cierre el modal
          document.querySelector("form").addEventListener("submit", function() {
          modal2.hide();
          //console.log(modal2.hide());
          });
      </script>
  
  {% endblock extrascripts %} {% endcomment %}

templates/calendarapp/tipo_actividad_academica.html
{% comment %} <form hx-post= "{{request.path}}" class="modal-content"> {% endcomment %}
  <div class="modal-content">
    <div class='modal-header text-center'>
        <h3 class="modal-title w-100">Tipo de Actividad Académica</h3> 
    </div>

    <div class="modal-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="tutoria" value="tutoria" checked>
                        <label class="form-check-label" for="tutoria">
                            Tutoría
                        </label>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12 mt-2">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="orientacion_academica" value="orientacion_academica">
                        <label class="form-check-label" for="orientacion_academica">
                            Orientación Académica
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="confirmar-btn">Confirmar</button>
    </div>  
</div>
  
  {% comment %} Este código agrega un escucha de evento click al botón. Cuando se hace clic en el botón, 
  el código verifica cuál de los elementos de radio está seleccionado y actualiza el href del botón en consecuencia.
   Si el href se actualiza, el código redirige el navegador a la nueva ubicación utilizando window.location.href.{% endcomment %}
  
  {% block extrascripts %}
      <script >
          const button = document.getElementById("confirmar-btn");
          const tutoiaRadio = document.getElementById("tutoria");
          const oriAcadeRadio = document.getElementById("orientacion_academica");
  
          button.addEventListener("click", () => {
            let href = "";
            if (tutoiaRadio.checked) {
              href = "{% url 'calendarapp:acti_academ_tutoria' %}";
            } else if (oriAcadeRadio.checked) {
              href = "{% url 'calendarapp:acti_academ_orientacion' %}";
            }
            if (href !== "") {
              window.location.href = href;
            }
          });
  
  
      </script>
  {% endblock extrascripts %}
  