accounts/urls.py
from django.urls import path

from accounts import views
from accounts.views import reset, profile

app_name = "accounts"


urlpatterns = [
    path("reset/", reset.ResetPassView.as_view(), name='reset'),
    path("resetconfirm/<str:pk>/<str:password_reset_token>", reset.ResetPassConfirmView.as_view(), name='resetconfirm'),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
    path("profile/", profile.ProfileView, name="profile"),
    path("cambiarcontrasenha/", reset.CambiarContrasenhaView.as_view(), name="cambiarcontrasenha"),
    
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
    path("", include("notify.urls")),
]

notify/urls.py
from django.urls import path
from notify.views import NotificationList, actualizar_notificacion_leida

app_name = "notify"

urlpatterns = [
    path("notificacion/", NotificationList.as_view(), name="notificaciones"),
    path("actualizarNotify/", actualizar_notificacion_leida, name="actualizar_notificacion"),
]

accounts/views/profile.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from accounts.models.user import Persona
from django.forms.models import model_to_dict

from accounts.forms import SignUpForm

#login_required, garantiza que el usuario esté autenticado antes de que se ejecute la vista. Usar solo para funciones, no para clases
@login_required
def ProfileView(request):
    try:
        current_user = request.user
        #https://stackoverflow.com/questions/21925671/convert-django-model-object-to-dict-with-all-of-the-fields-intact
        dict = model_to_dict(current_user)
        persona=  Persona.objects.get(pk= dict["id_persona"])
        context = {"user": current_user, "persona": persona}

        return render(request, "accounts/profile.html", context)
    except Exception as e:
        print(f"Se ha producido un error: {e}")

accounts/views/reset.py
from django.http import HttpResponse
from django.views.generic import View
from django.shortcuts import render, redirect
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from accounts.models.user import User
from accounts.forms import ResetPassForm, ResetPassConfirmation, ForgotPasswordTokenGenerator,CambiarContrasenha
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from dotenv import load_dotenv
load_dotenv()

#formulario de carga del correo para enviarle el token de restableciento
class ResetPassView(View):
    """ User reset password view """

    template_name = "accounts/password_reset_form.html"
    form_class = ResetPassForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            
            try:
                #enviamos el correo al usuario
                #obtenemos el mail y buscamos el objeto usuario
                destinatario= forms.cleaned_data['email']
                user =  User.objects.get(email= destinatario)
                #preparamos el token para el usuario
                reset_token_generator_object= ForgotPasswordTokenGenerator()
                password_reset_token= reset_token_generator_object.make_token(user)
                #verificar para no hacer de manera 
                base_url= 'http://0.0.0.0:8000/accounts/resetconfirm/'
                #base_url= reverse('resetconfirm')
                base_url= str(base_url)
                #base_url= reverse('resetconfirm', args=(user.pk, password_reset_token))
                forgot_password_urls= f'{base_url}{user.pk}/{password_reset_token}'
                #enviamos el correo
                enviarcorreo(forgot_password_urls, destinatario)
                return render(request, "accounts/password_reset_done.html") 
            except Exception as e:
                print(f"Se ha producido un error: {e}")

        #si so es valido volvemos a retonar el mismo objeto form para poder mostrar el error en pantalla    
        context = {"form": forms}
        return render(request, self.template_name, context)


#formulario de carga de correo para restablecer la contrasenha
class ResetPassConfirmView(View):
    """ User reset password view """

    template_name = "accounts/password_reset_confirm.html"
    form_class = ResetPassConfirmation

    pk= None
    reset_token_generator_object= None
    user= None

    #para mostrar el usuario, cuando se hace la llamada al base url
    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        try:
            #obtendremos los valores que recibira
            pk = kwargs.get('pk', None)
            password_reset_token = kwargs.get('password_reset_token', None)
            #si los datos son correctos se procede a validar si el token aun es valido para poder mostrar el formulario, caso contrario se direcciona al template de error
            if pk is not None or password_reset_token is not None:
                user= User.objects.get(pk= pk)
                reset_token_generator_object= ForgotPasswordTokenGenerator()
                if not reset_token_generator_object.check_token(user, password_reset_token):
                    #redireccionamos a la pantalla de error
                    return render(request, "accounts/error_token.html")
            else:
                pass           
                
        except Exception as e:
            print(f"Se ha producido un error: {e}")
            return render(request, "accounts/error_token.html")
        return render(request, self.template_name, context)

    #*args es para pasar n cantidad de parametros pero sin nombre(es na tupla), *kwargs se utiliza para recibir n cantidad de parametros pero con nombre, seria un diccionario
    #esto es para poder guardar lo que esta cargado en el formulario    
    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid(): 
            try:
                #obtendremos los valores que recibira
                pk = kwargs.get('pk', None)
                password_reset_token = kwargs.get('password_reset_token', None)
                #si los datos son correctos procedemos a guardar el objeto actualizado
                if pk is not None or password_reset_token is not None:
                    #print("Value of 'pk' argument:", pk)
                    #print("Value of 'password_reset_token' argument:", password_reset_token)
                    user= User.objects.get(pk= pk)
                    user.set_password(forms.cleaned_data["password1"])
                    user.save()
                    #redireccionamos al inicio de sesion
                    return redirect("accounts:signin")
            except Exception as e:
                print(f"Se ha producido un error: {e}")
        #si so es valido volvemos a retonar el mismo objeto form para poder mostrar el error en pantalla    
        context = {"form": forms}
        return render(request, self.template_name, context)

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

#configurar el setting.py, crear logica de envio de correo, obtener el mail del token
def enviarcorreo(forgot_password_urls, destinatario):
    # Configura tus credenciales de Outlook

    sender_email = os.getenv('SENDER_EMAIL')
    sender_password = os.getenv('SENDER_PASSWORD')

    # Configura el servidor SMTP de Outlook
    smtp_server = 'smtp-mail.outlook.com'
    smtp_port = 587  # Puerto de Outlook para TLS (587)

    # Crea un objeto SMTP
    server = smtplib.SMTP(smtp_server, smtp_port)

    # Inicia la conexión TLS (segura)
    server.starttls()

    # Inicia sesión en tu cuenta de Outlook
    server.login(sender_email, sender_password)

    # Crea el mensaje de correo con contenido HTML
    subject = 'Restablecer contraseña'
    recipient_email = destinatario

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = subject

    # Cuerpo del correo en formato HTML con la variable
    html_body = f"""
    <html>
    <body>
        <p>A continuación, un enlace que te ayudará a restablecer tu contraseña:</p>
        <p><a href="{forgot_password_urls}">Haz clic <strong>aquí</strong> para restablecer tu contraseña</a></p>
        <p>Atentamente,</p>
        <p>Equipo AcOms</p>
    </body>
    </html>
    """

    msg.attach(MIMEText(html_body, 'html'))

    try:
        # Envía el correo
        server.sendmail(sender_email, recipient_email, msg.as_string())
        # Cierra la conexión SMTP
        server.quit()
        print('Correo enviado con éxito')
    except Exception as e:
        print(f"Se ha producido un error: {e}")
        

class CambiarContrasenhaView(LoginRequiredMixin, View):

    template_name = "accounts/cambiar_contrasenha.html"
    form_class = CambiarContrasenha

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    #aqui procedemos a hacer el cambio
    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid(): 
            try:
                storage = messages.get_messages(request)
                for message in storage:
                    if message.level == messages.ERROR:
                        storage.discard(message)

                #aqui debemos validar si la contrasenha ingresada es el mismo que el usuario logeado actualmente
                current_user = request.user
                senha= forms.cleaned_data["contrasenha"]
                if current_user.check_password(senha):
                    # Contraseña correcta
                    current_user.set_password(forms.cleaned_data["password1"])
                    current_user.save()
                    #actualizamos los datos de la sesion actual 
                    update_session_auth_hash(request, request.user)
                    #ver que hacer una vez que ya este finalizado!
                    return HttpResponse(status= 204) #No content
                else:
                    messages.error(request, 'Los datos son incorrectos, vuelve a intentarlo.')
            except Exception as e:
                print(f"Se ha producido un error: {e}")

        #si so es valido volvemos a retonar el mismo objeto form para poder mostrar el error en pantalla
        context = {"form": forms}
        return render(request, self.template_name, context)
    

accounts/views/signin.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.conf import settings
from accounts.forms import SignInForm


class SignInView(View):
    """ User registration view """

    template_name = "accounts/signin.html"
    form_class = SignInForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            email = forms.cleaned_data["email"]
            password = forms.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect("calendarapp:calendar")
            else:
                messages.error(request, 'Los datos son incorrectos, vuelve a intentarlo.')
        context = {"form": forms}
        return render(request, self.template_name, context)

accounts/views/signout.py
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.conf import settings

def signout(request):
    logout(request)
    return redirect("accounts:signin")

accounts/views/signup.py
from django.views.generic import View
from django.shortcuts import render, redirect

from accounts.forms import SignUpForm
from django.conf import settings


class SignUpView(View):
    """ User registration view """

    template_name = "accounts/signup.html"
    form_class = SignUpForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect("accounts:signin")
        else:
            for field, errors in forms.errors.items():
                for error in errors:
                    print(f"Error en el campo {field}: {error}")
                    
        context = {"form": forms}
        return render(request, self.template_name, context)

templates/accounts/cambiar_contrasenha.html
{% comment %} el request.path se usa para poder usar la misma url del gest para el metodo post {% endcomment %}
<form hx-post= "{{request.path}}" class="modal-content">
{% csrf_token %}

  <div class='modal-header text-center'>
    <h3 class="modal-title w-100">Cambiar Contraseña</h3> 
  </div>  

  <p class="or">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <span class="text-danger"> {{ message }} </span>
            {% endfor %}
        </ul>
    {% endif %}
  </p>

  <div class="modal-body">
    <div class="col-md-12">
      <div class="form-group">
        <label class="label" for="password">Contraseña Actual</label>
        {{ form.contrasenha}}
        <span class="text-danger">{{ form.errors.contrasenha }}</span>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label class="label" for="password">Contraseña Nueva</label>
        {{ form.password1 }}
        <span class="text-danger">{{ form.errors.password1 }}</span>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
          <label class="label" for="password">Confirmar Contraseña</label>
          {{ form.password2 }}
          <span class="text-danger">{{ form.errors.password2 }}</span>
        </div>
    </div>

    <div class="modal-footer">
      {% comment %} cuidado con las versiones de Bootstrap! {% endcomment %}
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
    </div>  
        
  </div>
</form>  

{% comment %} <form hx-post="{{ request.path }}" class="modal-content">
  {% csrf_token %}
  
  <div class='modal-header'>
    <h1> Cambiar Contraseña </h1>
  </div>

  <p class="or">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <span class="text-danger"> {{ message }} </span>
            {% endfor %}
        </ul>
    {% endif %}
  </p>

  <div class="modal-body">

    <div class="col-md-12">
      <div class="form-group">
        <label class="label" for="password">Contraseña Actual</label>
        {{ form.contrasenha}}
        <span class="text-danger">{{ form.errors.contrasenha }}</span>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label class="label" for="password">Contraseña Nueva</label>
        {{ form.password1 }}
        <span class="text-danger">{{ form.errors.password1 }}</span>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
          <label class="label" for="password">Confirmar Contraseña</label>
          {{ form.password2 }}
          <span class="text-danger">{{ form.errors.password2 }}</span>
        </div>
    </div>

  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
  </div>

</form> {% endcomment %}

templates/accounts/error_token.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
    <head>
        <title>Event Calendar</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="wrap d-md-flex">
                            <div class="text-wrap p-4 p-lg-5 d-flex img" style="background-image: url({% static 'images/UAA.jpg' %});">
                                <div class="text w-100">
                                    {% comment %} <h2 class="mb-4">Welcome to Event Calendar</h2>
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p> {% endcomment %}
                                </div>
                            </div>
                            <div class="login-wrap p-4 p-md-5">
                                <div class="row justify-content-center py-md-5">
                                    <div class="col-lg-9">
                                        {% comment %} <div class="social-wrap">
                                            <h2 class="mb-3 text-center"> Restablecer contraseña</h3>
                                        </div> {% endcomment %}
                                        {% comment %} <div >
                                            <p>A continuación ingrese su nueva contraseña:</p>
                                        </div> {% endcomment %}
    
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="label" for="password">Token de recuperacion invalido o expirado, vuelva a intentarlo.</label>
                                                    </div>
                                                </div>
                                            
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <a href="{% url 'accounts:reset' %}">Restablecer Constraseña</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% include 'base/js.html' %}
    </body>
</html>

templates/accounts/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% comment %} {% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
        <p>Event Dashboard</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
    </ul>
{% endblock breadcrumb %} {% endcomment %}

{% block content %}
<div class="row">
    {% comment %} <div class="col-md-6 col-lg-3">
        <div class="widget-small primary coloured-icon">
            <i class="icon fa fa-files-o fa-3x"></i>
            <div class="info">
                <h4>Total Completed Events</h4>
                <p><b>{{ total_event }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small info coloured-icon">
            <i class="icon fa fa-thumbs-o-up fa-3x"></i>
            <div class="info">
                <h4>Total Running Events</h4>
                <p><b>{{ running_events.count }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small warning coloured-icon">
            <i class="icon fa fa-users fa-3x"></i>
            <div class="info">
                <h4>Total Participants</h4>
                <p><b>10</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small danger coloured-icon">
            <i class="icon fa fa-star fa-3x"></i>
            <div class="info">
                <h4>Stars</h4>
                <p><b>500</b></p>
            </div>
        </div>
    </div> {% endcomment %}
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div> {% comment %} <div class="table-responsive"> {% endcomment %}
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="mb-3 row">
                                    <label for="staticEmail" class="col-sm-2 col-form-label">Correo:</label>
                                    <div class="col-sm-10">
                                      {{ user.email }}
                                    </div>
                                  </div>
                                  <div class="mb-3 row">
                                    <label for="staticFecha" class="col-sm-2 col-form-label">Fecha de alta:</label>
                                    <div class="col-sm-10">
                                        {{ user.date_joined|date:"d/m/Y" }}
                                    </div>
                                  </div>
                                  <div class="mb-3 row">
                                    <label for="staticNombre" class="col-sm-2 col-form-label">Nombre:</label>
                                    <div class="col-sm-10">
                                        {% comment %} Se puede usar funciones filters dentro de jinja {% endcomment %}
                                        {{ persona.nombre|add:' '|title}}{{ persona.apellido|title }}
                                    </div>
                                  </div>

                                  <div class="col-auto">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" hx-get="{% url 'accounts:cambiarcontrasenha' %}" hx-target="#dialog">
                                        Cambiar Contraseña
                                    </button>
                                    {% comment %} {% include 'accounts/cambiar_contrasenha.html' %} {% endcomment %}
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

{% block extrascripts %}
     <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

templates/accounts/signin.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
    <head>
        <title>Sign In | Event Calendar</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="wrap d-md-flex">
                            <div class="text-wrap p-4 p-lg-5 d-flex img" style="background-image: url({% static 'images/UAA.jpg' %});">
                                <div class="text w-100">
                                    <h2 class="mb-4"></h2>
                                    {% comment %} <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p> {% endcomment %}
                                </div>
                            </div>
                            <div class="login-wrap p-4 p-md-5">
                                <div class="row justify-content-center py-md-5">
                                    <div class="col-lg-9">
                                        <div class="social-wrap">
                                            {% comment %} <h3 class="mb-3 text-center">Signin with this services</h3>
                                            <p class="social-media d-flex justify-content-center">
                                                <a href="#" class="social-icon google d-flex align-items-center justify-content-center"><span class="fa fa-google"></span></a>
                                                <a href="#" class="social-icon facebook d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
                                                <a href="#" class="social-icon twitter d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
                                            </p> {% endcomment %}
                                            <p class="or">
                                                 <span>Bienvenido a AcOMs</span> 

                                                {% if messages %}
                                                    <ul class="messages">
                                                        {% for message in messages %}
                                                        <span class="text-danger"> {{ message }} </span>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}

                                            </p>
                                        </div>
                                        <form action="#" method="post" class="signup-form">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="label" for="email">Email</label>
                                                        {{ form.email }}
                                                        <span class="text-danger">{{ form.errors.email }}</span>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="label" for="password">Contraseña</label>
                                                        {{ form.password }}
                                                        <span class="text-danger">{{ form.errors.password }}</span>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <div class="w-100">
                                            <p class="mt-4">Todavia no tiene cuenta? <a href="{% url 'accounts:signup' %}">Registrarse</a></p>
                                        </div>
                                        <div class="w-100">
                                            <p class="mt-4">Ha olvidado su contraseña? <a href="{% url 'accounts:reset' %}">Restablecer Contraseña</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% include 'base/js.html' %}
        
    </body>
</html>