accounts/urls.py
from django.urls import path

from accounts import views
from accounts.views import reset, profile

app_name = "accounts"


urlpatterns = [
    path("reset/", reset.ResetPassView.as_view(), name='reset'),
    path("resetconfirm/<str:pk>/<str:password_reset_token>", reset.ResetPassConfirmView.as_view(), name='resetconfirm'),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
    path("profile/", profile.ProfileView, name="profile"),
    path("cambiarcontrasenha/", reset.CambiarContrasenhaView.as_view(), name="cambiarcontrasenha"),
    
]

calendarapp/urls.py
from django.urls import path
from calendarapp.views.other_views import TutoriaCreateView, formCalendarioFuncDoc, obtener_horarios_cita ,EditCalendarioFuncDoc, tipo_cita, tipo_acti_academ, AddCalendarioFuncDoc, delCalendarioFuncDoc, ori_academica, actualizar_campo, CitaTutoriaCreateView, CitaOrientacionAcademicaCreateView, CitaTutoriaUpdateView, CitaOrientacionAcademicaUpdateView, CitaTutoriaDetalle, CitaOrientacionAcademicaDetalle, CitaTutoriaIniciarView, CitaOrientacionAcademicaIniciarView, OrientacionAcademicaCreateView, TutoriaDetalle, OrientacionAcademicaDetalle, TutoriaUpdateView, TareasView, OrientacionAcademicaUpdateView, AddTarea#ListCalendarioFuncDoc

from calendarapp.views import CalendarView, CalendarViewNew, AllEventsListView, RunningEventsListView, DetalleCita, CancelarCita
from calendarapp.views.event_list import AprobarCita, ActividadesAcademicasListView, RunningActividadesAcademicasListView, DetalleActividadesAcademicas, CancelarActividadAcademica, FinalizarActividadAcademica, CancelarTarea, IniciarTarea, FinalizarTarea, About, RechazarCita
from calendarapp.views.reportes import ReporteTutoriaView, actualizar_campos_reportes, ReporteOrientacionAcademicaView, ReporteCitasView, ReporteTareasView
app_name = "calendarapp"


urlpatterns = [
    
    path("formulariofundoc/", formCalendarioFuncDoc, name="form_cal_func_doc"),
    path("formulariofundoc/edit/<int:pk>/", EditCalendarioFuncDoc, name="edit_cal_func_doc"),
    path("formulariofundoc/add/", AddCalendarioFuncDoc, name="add_cal_func_doc"),
    path("formulariofundoc/delete/<int:pk>/", delCalendarioFuncDoc, name="del_cal_func_doc"),
    path("calender/", CalendarViewNew.as_view(), name="calendar"), #este es el calendario
    path("calenders/", CalendarView.as_view(), name="calendars"), #este es el dashboard
    
    #Citas
    path("tipoCita/", tipo_cita, name="tipo_cita"),
    path('actualizar_campo/', actualizar_campo, name='actualizar_campo'),
    path("detallesCita/<int:id_cita>/", DetalleCita, name="detalles_cita"),
    path("cita/confirmar/<int:id_cita>/", AprobarCita, name="confirmar_cita"),
    path("cita/cancelar/<int:id_cita>/", CancelarCita, name="cancelar_cita"),
    path("cita/rechazar/<int:id_cita>/", RechazarCita, name="rechazar_cita"),
    path("tutoria/", CitaTutoriaCreateView.as_view(), name="tuto"),
    path("orientacionAcademica/", CitaOrientacionAcademicaCreateView.as_view(), name="academica"),
    path("modificarCitaTutoria/<int:pk>/", CitaTutoriaUpdateView.as_view(), name="modificar_cita_tutoria"),
    path("modificarCitaOriAcademica/<int:pk>/", CitaOrientacionAcademicaUpdateView.as_view(), name="modificar_cita_ori_academica"),
    path('obtener_horarios_cita/', obtener_horarios_cita),
    path("all-event-list/", AllEventsListView.as_view(), name="all_events"),
    path("running-event-list/<str:tipo_cita>/",RunningEventsListView.as_view(),name="running_events"), 
    path("moredetallesCitaTutoria/<int:pk>/", CitaTutoriaDetalle.as_view() , name="more_detalles_cita_tutoria"),
    path("moredetallesCitaOriAcadem/<int:pk>/", CitaOrientacionAcademicaDetalle.as_view() , name="more_cita_detalles_ori_academica"),
    path("iniciarCitaTutoria/<int:pk>/", CitaTutoriaIniciarView.as_view() , name="iniciar_cita_tutoria"),
    path("iniciarCitaOrientacionAcademica/<int:pk>/", CitaOrientacionAcademicaIniciarView.as_view() , name="iniciar_cita_ori_academ"),
    
    
    
    
    #Actividades Academicas
    path("tipoActiAcadem/", tipo_acti_academ, name="tipo_acti_academ"),
    path("all-acti_academ-list/", ActividadesAcademicasListView.as_view(), name="all_acti_academ"),
    path("running-acti_academ-list/<str:tipo_cita>/",RunningActividadesAcademicasListView.as_view(),name="running_acti_academ"), 
    path("actiAcademTutoria/", TutoriaCreateView.as_view(), name="acti_academ_tutoria"),
    path("actiAcademOrientacion/", OrientacionAcademicaCreateView.as_view(), name="acti_academ_orientacion"),
    path("detallesActiAcademicas/<int:id_tutoria>/<int:id_ori_academ>/", DetalleActividadesAcademicas, name="detalles_acti_academ"),
    path("moredetallesTutoria/<int:pk>/", TutoriaDetalle.as_view() , name="more_detalles_tutoria"),
    path("moredetallesOrientacionAcademica/<int:pk>/", OrientacionAcademicaDetalle.as_view() , name="more_detalles_ori_academica"),
    path("actividad_academica/cancelar/<int:id_tutoria>/<int:id_ori_academ>/", CancelarActividadAcademica, name="cancelar_actividad_academica"),
    path("actividad_academica/finalizar/<int:id_tutoria>/<int:id_ori_academ>/", FinalizarActividadAcademica, name="finalizar_actividad_academica"),
    path("modificarTutoria/<int:pk>/", TutoriaUpdateView.as_view(), name="modificar_tutoria"),
    path("modificarOrientacion/<int:pk>/", OrientacionAcademicaUpdateView.as_view(), name="modificar_orientacion"),
    
    #Tareas
    path("tareas/", TareasView.as_view(), name="tareas"),
    path("tarea/finalizar/<int:id_tarea>/", FinalizarTarea, name="finalizar_tarea"),
    path("tarea/iniciar/<int:id_tarea>/", IniciarTarea, name="iniciar_tarea"),
    path("tarea/cancelar/<int:id_tarea>/", CancelarTarea, name="cancelar_tarea"),
    path("nuevaTarea/", AddTarea, name="nueva_tarea"),
    
    
    #adicionales
    path("about/", About, name="about"),
    
    
    #reportes
    path("reporte/tutoria/", ReporteTutoriaView.as_view(), name="reporte_tutoria"),
    path("reporte/cita/", ReporteCitasView.as_view(), name="reporte_cita"),
    path("reporte/orientacion/", ReporteOrientacionAcademicaView.as_view(), name="reporte_orientacion"),
    path("reporte/tarea/", ReporteTareasView.as_view(), name="reporte_tarea"),
    path('actualizar_campos_reportes/', actualizar_campos_reportes, name='actualizar_campos_reportes'),
    
    
    
    
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
    path("", include("notify.urls")),
]

notify/urls.py
from django.urls import path
from notify.views import NotificationList, actualizar_notificacion_leida

app_name = "notify"

urlpatterns = [
    path("notificacion/", NotificationList.as_view(), name="notificaciones"),
    path("actualizarNotify/", actualizar_notificacion_leida, name="actualizar_notificacion"),
]

calendarapp/models/event.py
from django.db import models
from django.db.models import F
from django.forms import model_to_dict
from calendarapp.models import EventAbstract
from django.db.models import Q, CheckConstraint
from itertools import chain
import os
from dotenv import load_dotenv
load_dotenv()

"""models.Manager es una clase de Django que proporciona un mecanismo para realizar consultas a la base de datos y realizar operaciones en los modelos de manera más fácil y eficiente. Cada modelo de Django tiene al menos un objeto Manager asociado a él de forma predeterminada.

Los objetos Manager de los modelos de Django son responsables de proporcionar un conjunto de métodos para interactuar con la base de datos. Por ejemplo, objects.all() devuelve todos los registros de la base de datos para un modelo específico, mientras que objects.filter() permite realizar consultas más avanzadas para recuperar un subconjunto específico de registros.

También puedes crear tus propios objetos Manager personalizados para extender las funcionalidades por defecto y ajustar las consultas a tus necesidades específicas.

En resumen, models.Manager es un componente clave de Django que proporciona una API de consulta a la base de datos para modelos de Django, y permite interactuar de manera eficiente y efectiva con la información almacenada en la base de datos."""


class EventManager(models.Manager):
    """ Event manager. select_related: Sin embargo, debes tener en cuenta que esta optimización solo funciona para relaciones ForeignKey y OneToOneField. Si estás trabajando con relaciones ManyToManyField, deberás utilizar el método prefetch_related para optimizar las consultas. """

    def get_all_events(self):
        
        events = Cita.objects.select_related("id_cita")

        return events
    """como hacer un inner join con dos modelos y obtener columnas seleccionadas con filtros especificos en django"""
    
    def get_all_acti_academ(self):
        
        tutorias = Tutoria.objects.select_related("id_tutoria").annotate(id_actividad_academica=F("id_tutoria")).filter(id_cita= None)
        orientaciones = OrientacionAcademica.objects.select_related("id_orientacion_academica").annotate(id_actividad_academica=F("id_orientacion_academica")).filter(id_cita= None)
        
        # Combinar los dos querysets en una sola variable
        events= list(chain(tutorias, orientaciones))

        return events
    
    def get_all_actividades(self):
        #actividades con citas
        citas = Cita.objects.select_related("id_cita")
        #tutorias sin citas
        tutorias = Tutoria.objects.select_related("id_tutoria").filter(id_cita= None)
        #orientaciones sin citas
        orientaciones = OrientacionAcademica.objects.select_related("id_orientacion_academica").filter(id_cita= None)

        # Combinar los dos querysets en una sola variable
        all_events= list(chain(citas, tutorias, orientaciones))

        return all_events

    #este usamos para traer un solo tipo de cita, ya sea de tipo tutoria u orientacion academica 
    def get_running_events(self, tipo_cita):
        if tipo_cita == 'Tutoria':
            
            running_events = Cita.objects.filter(es_tutoria= True).select_related("id_cita")
        elif tipo_cita== "OriAcademica":
            running_events = Cita.objects.filter(es_orientacion_academica= True).select_related("id_cita")
        else: 
            running_events = Cita.objects.select_related("id_cita")
            
        """ .filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")"""
        return running_events
    
    def get_running_acti_academ(self, tipo_cita):
        if tipo_cita == 'Tutoria':
            running_events = Tutoria.objects.select_related("id_tutoria").annotate(id_actividad_academica=F("id_tutoria")).filter(id_cita= None)
            
        elif tipo_cita== "OriAcademica":
            running_events = OrientacionAcademica.objects.select_related("id_orientacion_academica").annotate(id_actividad_academica=F("id_orientacion_academica")).filter(id_cita= None)
        else: 
            tutorias = Tutoria.objects.select_related("id_tutoria").annotate(id_actividad_academica=F("id_tutoria")).filter(id_cita= None)
            orientaciones = OrientacionAcademica.objects.select_related("id_orientacion_academica").annotate(id_actividad_academica=F("id_orientacion_academica")).filter(id_cita= None)
            running_events = list(chain(tutorias, orientaciones))

        return running_events
    
"""Vamos a considerar que Event es la tabla de Actividad Academica"""
"""Modificaremos los nombres de los campos para que concidan con las de nuestro modelo"""
class EstadoActividadAcademica(models.Model):
    id_estado_actividad_academica= models.AutoField(primary_key=True)
    descripcion_estado_actividad_academica= models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion_estado_actividad_academica

from accounts.models.user import Facultad, Materia, Departamento, FuncionarioDocente, Persona
from calendarapp.models.calendario import Convocatoria

class Event(EventAbstract):
    """ Event model """

    id_estado_actividad_academica= models.ForeignKey(EstadoActividadAcademica, on_delete=models.CASCADE, related_name='estado_acti_aca')
    id_convocatoria= models.ForeignKey(Convocatoria, on_delete=models.CASCADE, related_name='convocatoria')
    id_facultad= models.ForeignKey(Facultad, on_delete=models.CASCADE, related_name='facultad')
    id_materia= models.ForeignKey(Materia, on_delete=models.CASCADE, blank=True, null=True)
    id_departamento= models.ForeignKey(Departamento, on_delete=models.CASCADE, related_name='departamento', blank=True, null=True)
    id_funcionario_docente_encargado= models.ForeignKey(FuncionarioDocente, on_delete=models.CASCADE, related_name='funcionario_docente_encarcado')
    id_persona_solicitante= models.ForeignKey(Persona, on_delete=models.CASCADE, blank=True, null=True)
    id_persona_alta= models.ForeignKey(Persona, on_delete=models.CASCADE, related_name='persona_alta')
    datetime_inicio_estimado = models.DateTimeField()
    datetime_fin_estimado = models.DateTimeField()
    datetime_inicio_real = models.DateTimeField(null= True, blank=True)
    datetime_fin_real = models.DateTimeField(null= True, blank=True)
    datetime_registro = models.DateTimeField() #auto_now=True
    observacion= models.CharField(max_length=500, null= True, blank=True)
    nro_curso= models.CharField(max_length=30, null= True, blank=True)
    id_persona_ultima_modificacion= models.ForeignKey(Persona, on_delete=models.CASCADE, blank=True, null=True, related_name='evento_modificacion')

    objects = EventManager()

    def __str__(self):
        return self.id_actividad_academica.__str__() 
    class Meta:
        verbose_name_plural = "Actividades Academicas"
        #permisos personalizados
        permissions= [('iniciar_cita', 'Iniciar cita'), ('finalizar_cita', 'Finalizar cita' ), ('editar_cita', 'Editar cita'), ('cancelar_cita', 'Cancelar cita'), ('confirmar_cita', 'Confirmar cita'), ('registrar_cita', 'registar cita'),('rechazar_cita', 'rechazar cita'), ('editar_actividad_academica', 'Editar Actividad Academica'), ('registrar_actividad_academica', 'Registrar Actividad Academica'), ('cancelar_actividad_academica', 'Cancelar Actividad Academica'), ('finalizar_actividad_academica', 'Finalizar Actividad Academica')]

class DetalleActividadAcademica(models.Model):
    id_detalle_actividad_Academica= models.AutoField(primary_key=True)
    id_participante= models.ForeignKey(Persona, on_delete=models.CASCADE, related_name='persona_participante')
    id_actividad_academica= models.ForeignKey(Event, on_delete=models.CASCADE, related_name='actividad_academica')
    
    def toJSON(self):
        item = model_to_dict(self)
        item['value'] = self.id_participante.nombre + ' ' + self.id_participante.apellido 
        return item
    

class UnidadMedida(models.Model):
    id_unidad_medida = models.AutoField(primary_key=True)
    descripcion_unidad_medida= models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion_unidad_medida
    
    class Meta:
        verbose_name_plural = "Unidades de Medida"

class Parametro(models.Model):
    id_parametro = models.AutoField(primary_key=True)
    id_unidad_medida =  models.ForeignKey(UnidadMedida, on_delete=models.CASCADE, related_name='unidad_medida_parametro')
    descripcion_parametro = models.CharField(max_length=50, null= True)
    valor = models.IntegerField()
    es_orientacion_academica = models.BooleanField(default=False) 
    es_tutoria = models.BooleanField(default=False)
    
    class Meta:
            constraints = [
                CheckConstraint(
                    check=Q(es_tutoria=True, es_orientacion_academica=False) |
                        Q(es_tutoria=False, es_orientacion_academica=True) ,
                    name='solo_uno_puede_ser_true'
                )
            ]

            verbose_name_plural = "Parametros"
    
    def __str__(self):
        return '%s %s' % (self.descripcion_parametro, self.valor) 
        
class Cita(models.Model):
    id_cita= models.ForeignKey(Event, on_delete=models.CASCADE, related_name='ori_academ_cita', primary_key=True)
    id_parametro = models.ForeignKey(Parametro, on_delete=models.CASCADE, related_name='parametro_cita')
    es_tutoria = models.BooleanField(default=False)
    es_orientacion_academica = models.BooleanField(default=False)
    es_notificable = models.BooleanField(default=True)
    motivo= models.CharField(max_length=500, null= True)
    motivo_cancelacion = models.CharField(max_length=500, null= True)
    motivo_rechazo = models.CharField(max_length=500, null= True)
    

    class Meta:
            constraints = [
                CheckConstraint(

templates/add_member.html
{% extends 'base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Wellcome, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + New Event </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

templates/eliminar_registro.html
{% load static %}
<form hx-post= "{{request.path}}" class="modal-content" id="formeliminar"> 
      <div class='modal-header text-center'>
        <h3 class="modal-title w-100">Eliminar Registro</h3> 
      </div>

      <p class="or">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <span class="text-danger"> {{ message }} </span>
                {% endfor %}
            </ul>
        {% endif %} 
      </p> 

        <div class="col-md-12">
            <div class="form-group">
              <label class="label" for="hora_fin">Está seguro que desea eliminar el registro?</label>
            </div>
        </div>
    
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cerrar">Cancelar</button>
          <button type="button" class="btn btn-primary" id="eliminar">Aceptar</button>
        </div>  
            
      </div>
</form>  

<div id="avisoProcesando" class="aviso-procesando">
  <p>Procesando...</p>
  <img src="{% static 'images/loading.gif' %}" alt="Procesando">

</div>

<!-- Jquery Confirm -->
<link rel="stylesheet" href="{% static 'lib_extras/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
<script src="{% static 'lib_extras/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
<!-- Functions -->
<script src="{% static 'js/functions.js' %}"></script>

<script>
  
  $(document).ready(function() {
      // Obtener el formulario y el botón de cancelar
      var form = document.getElementById('formeliminar');
      var botonEliminar= document.getElementById('eliminar');
      var botonCerrar = document.getElementById('cerrar');

      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
      
      // Agregar el evento click al botón de cancelar
      botonEliminar.addEventListener('click', function() {
      
          botonEliminar.disabled = true;
          botonCerrar.disabled = true;
          // Mostrar el aviso de procesando
          mostrarAvisoDeProcesando();

          // Agregar el motivo al atributo hx-post del formulario
          //form.setAttribute('hx-post', form.getAttribute('hx-post') + '?motivo=' + encodeURIComponent(motivo_cancelacion));


          $.ajax({
            url: form.getAttribute('hx-post'),
            type: 'POST',
          }).done(function (data) {
            ocultarAvisoDeProcesando();
            // Habilitar los botones
            //botonEliminar.disabled = false;
            //botonCerrar.disabled = false;

              location.reload();
          }).fail(function (jqXHR, textStatus, errorThrown) {
              ocultarAvisoDeProcesando();
              // Habilitar los botones
              botonEliminar.disabled = false;
              botonCerrar.disabled = false;

              alert(textStatus + ': ' + errorThrown);
          }).always(function (data) {

          });
        
      });

      function mostrarAvisoDeProcesando() {
        document.getElementById('avisoProcesando').style.display = 'flex'; // Muestra el aviso
      }
    
      function ocultarAvisoDeProcesando() {
        document.getElementById('avisoProcesando').style.display = 'none'; // Oculta el aviso
      }
  });
</script>

templates/event-details.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
        </div>

        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}